### PR TITLE
Added optional support for ranges in the profile download mode

### PR DESCRIPTION
**Pull request by Hekkun**
Hello,

I made some minor updates to the code to add the capability to specify URL ranges in profile download mode. The user is given the ability to specify a starting post URL and ending post URL, and only posts from within that range will be downloaded in this mode. 

Screenshot 2024-09-02 200946

_Note: You can provide a **0** to either of the two inputs, and it will use it as a shortcut for either the newest or oldest post._

Users can skip this range feature entirely simply by pressing 1 or just tapping Enter.

Screenshot 2024-09-02 201443

I realize there is a more involved way to do this using the JSON file; however, I found this inline method quicker and easier to use. The cases where I believe it would be useful are:

- When the download of a large profile gets interrupted (this happened several times today, prompting me to write this update)
    - Now you can easily resume the download by specifying the last successful post as 'start' and **0** as the 'end' (i.e. oldest post)
- When a number of new posts are uploaded but you don't wish to redownload the entire profile
    - You can download the new files by specifying **0** as the 'start' (i.e. newest post) and the last post you previously downloaded as 'end'

I have made identical updates to both the EN and PT _profile.py_ files. Unfortunately, I had to leave the text in English as I don't know the appropriate translations. However, the functionality is made identical to prevent any overhead in project maintenance.

If you feel like this feature may be of any use to others, it would be great if you would consider my PR. I would be happy to implement any fixes or modifications as per this project's requirements.

Thank you for developing this extremely useful code!

### CODE REVIEW

**Comment by e43b** [comment]
> Hello,
> 
> I made some minor updates to the code to add the capability to specify URL ranges in profile download mode. The user is given the ability to specify a starting post URL and ending post URL, and only posts from within that range will be downloaded in this mode.
> 
> Screenshot 2024-09-02 200946
> 
> _Note: You can provide a **0** to either of the two inputs, and it will use it as a shortcut for either the newest or oldest post._
> 
> Users can skip this range feature entirely simply by pressing 1 or just tapping Enter.
> 
> Screenshot 2024-09-02 201443
> 
> I realize there is a more involved way to do this using the JSON file; however, I found this inline method quicker and easier to use. The cases where I believe it would be useful are:
> 
> * When the download of a large profile gets interrupted (this happened several times today, prompting me to write this update)
>   
>   * Now you can easily resume the download by specifying the last successful post as 'start' and **0** as the 'end' (i.e. oldest post)
> * When a number of new posts are uploaded but you don't wish to redownload the entire profile
>   
>   * You can download the new files by specifying **0** as the 'start' (i.e. newest post) and the last post you previously downloaded as 'end'
> 
> I have made identical updates to both the EN and PT _profile.py_ files. Unfortunately, I had to leave the text in English as I don't know the appropriate translations. However, the functionality is made identical to prevent any overhead in project maintenance.
> 
> If you feel like this feature may be of any use to others, it would be great if you would consider my PR. I would be happy to implement any fixes or modifications as per this project's requirements.
> 
> Thank you for developing this extremely useful code!

Perfect, I tested it here and found it very practical, I'm going to merge it here, translate the code into Portuguese and fix the Readme

**Comment by Hekkun** [comment]
Thank you very much for the quick update and for taking care of the translation!

**Comment by Hekkun** [comment]
One more quick tip: due to way the code is written, you don't explicitly need to provide the full URL of a post. All you need is the ID at the end. Usually, you can find this easily from your download area (don't need to even open the website).

image

image

**Comment by e43b** [comment]
> One more quick tip: due to way the code is written, you don't explicitly need to provide the full URL of a post. All you need is the ID at the end. Usually, you can find this easily from your download area (don't need to even open the website).
> 
> image
> 
> image

Got it, very nice

**Pull request merged**
